# Usa el SDK de .NET para compilar
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

# Copiamos los archivos de los proyectos
COPY QualfixAdmin/QualfixAdmin.csproj QualfixAdmin/
COPY QualfixAdmin.dal/QualfixAdmin.dal.csproj QualfixAdmin.dal/
COPY QualfixAdmin.model/QualfixAdmin.model.csproj QualfixAdmin.model/
COPY QualfixAdmin.Services/QualfixAdmin.Services.csproj QualfixAdmin.Services/

# Restaurar dependencias
RUN dotnet restore QualfixAdmin/QualfixAdmin.csproj

# Ahora copiamos todo el contenido
COPY . .

# Publicamos la app
WORKDIR /src/QualfixAdmin
RUN dotnet publish -c Release -o /app/publish

# Ahora creamos la imagen final
FROM mcr.microsoft.com/dotnet/aspnet:8.0

WORKDIR /app
COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "QualfixAdmin.dll"]
