// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QualfixAdmin.dal.DBContext;

#nullable disable

namespace QualfixAdmin.dal.Migrations
{
    [DbContext(typeof(QualfixAdminContext))]
    partial class QualfixAdminContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QualfixAdmin.model.QualfixAdminData.Ciudad", b =>
                {
                    b.Property<int>("CiudadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CiudadID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CiudadId"));

                    b.Property<int?>("EstadoId")
                        .HasColumnType("integer")
                        .HasColumnName("EstadoID");

                    b.Property<string>("Nombre")
                        .HasMaxLength(90)
                        .IsUnicode(false)
                        .HasColumnType("character varying(90)");

                    b.HasKey("CiudadId")
                        .HasName("PK_Ciudad");

                    b.ToTable("Ciudad", (string)null);
                });

            modelBuilder.Entity("QualfixAdmin.model.QualfixAdminData.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ClienteID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Calle")
                        .HasColumnType("text");

                    b.Property<int?>("CiudadId")
                        .HasColumnType("integer")
                        .HasColumnName("CiudadID");

                    b.Property<string>("Colonia")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("CorreoElectronico")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Cp")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CP");

                    b.Property<string>("Cruzamientos")
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsUnicode(false)
                        .HasColumnType("text");

                    b.Property<int?>("EstadoId")
                        .HasColumnType("integer")
                        .HasColumnName("EstadoID");

                    b.Property<string>("Fax")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("InformacionFiscalId")
                        .HasColumnType("integer")
                        .HasColumnName("InformacionFiscalID");

                    b.Property<string>("NombreComercial")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NumeroExterior")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NumeroInterior")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("PaisId")
                        .HasColumnType("integer")
                        .HasColumnName("PaisID");

                    b.Property<string>("Telefonos")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)");

                    b.HasKey("ClienteId")
                        .HasName("PK_Cliente");

                    b.HasIndex("CiudadId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("InformacionFiscalId");

                    b.HasIndex("PaisId");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("QualfixAdmin.model.QualfixAdminData.ConfiguracionCfdi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cuenta")
                        .HasColumnType("text");

                    b.Property<string>("FileCer")
                        .HasColumnType("text")
                        .HasColumnName("fileCer");

                    b.Property<string>("FileKey")
                        .HasColumnType("text")
                        .HasColumnName("fileKey");

                    b.Property<string>("FilePasswordKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("filePasswordKey");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NameFileCer")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nameFileCer");

                    b.Property<string>("NameFileKey")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nameFileKey");

                    b.Property<string>("PasswordUsuario")
                        .HasColumnType("text");

                    b.Property<string>("Usuario")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK_ConfiguracionId");

                    b.ToTable("ConfiguracionCFDI", (string)null);
                });

            modelBuilder.Entity("QualfixAdmin.model.QualfixAdminData.Estado", b =>
                {
                    b.Property<int>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("EstadoID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EstadoId"));

                    b.Property<string>("Nombre")
                        .HasMaxLength(90)
                        .IsUnicode(false)
                        .HasColumnType("character varying(90)");

                    b.Property<int>("PaisId")
                        .HasColumnType("integer")
                        .HasColumnName("PaisID");

                    b.HasKey("EstadoId")
                        .HasName("PK_EstadoId");

                    b.ToTable("Estado", (string)null);
                });

            modelBuilder.Entity("QualfixAdmin.model.QualfixAdminData.Imagen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ReporteId")
                        .HasColumnType("integer");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("Tamaño")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ReporteId");

                    b.ToTable("Imagen");
                });

            modelBuilder.Entity("QualfixAdmin.model.QualfixAdminData.InformacionFiscals", b =>
                {
                    b.Property<int>("InformacionFiscalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("InformacionFiscalID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InformacionFiscalId"));

                    b.Property<int?>("CiudadId")
                        .HasColumnType("integer")
                        .HasColumnName("CiudadID");

                    b.Property<string>("Colonia")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Cp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CP");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("EstadoId")
                        .HasColumnType("integer")
                        .HasColumnName("EstadoID");

                    b.Property<string>("Localidad")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Municipio")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NumeroExterior")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("NumeroInterior")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int?>("PaisId")
                        .HasColumnType("integer")
                        .HasColumnName("PaisID");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Referencia")
                        .HasColumnType("text");

                    b.Property<int?>("RegFiscalId")
                        .HasColumnType("integer")
                        .HasColumnName("RegFiscalID");

                    b.Property<string>("Rfc")
                        .HasMaxLength(90)
                        .HasColumnType("character varying(90)")
                        .HasColumnName("RFC");

                    b.HasKey("InformacionFiscalId")
                        .HasName("PK_RegimenFIscal");

                    b.HasIndex("CiudadId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("PaisId");

                    b.HasIndex("RegFiscalId");

                    b.ToTable("InformacionFIscal", (string)null);
                });

            modelBuilder.Entity("QualfixAdmin.model.QualfixAdminData.Pai", b =>
                {
                    b.Property<int>("PaisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PaisId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaisId"));

                    b.Property<string>("Nombre")
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.Property<string>("SimboloMoneda")
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("SimboloMoneda");

                    b.Property<string>("TipoMoneda")
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("TipoMoneda");

                    b.HasKey("PaisId")
                        .HasName("PK_Pais");

                    b.ToTable("Pais", (string)null);
                });

            modelBuilder.Entity("QualfixAdmin.model.QualfixAdminData.Productos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("Descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.HasKey("Id")
                        .HasName("PK_ProductoId");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("QualfixAdmin.model.QualfixAdminData.RegimenFiscal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CodeRegimenFiscal")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("character varying(250)");

                    b.Property<bool?>("Fisica")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Moral")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("Id")
                        .HasName("PK_RegimenFiscal_1");

                    b.ToTable("RegimenFiscal", (string)null);
                });

            modelBuilder.Entity("QualfixAdmin.model.QualfixAdminData.Reporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Fecha_Recibido")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Fecha_Solicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero_Celular")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Reporte");
                });

            modelBuilder.Entity("QualfixAdmin.model.TipoDeLicencia", b =>
                {
                    b.Property<int?>("TipoLicenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("TipoLicenciaId"));

                    b.Property<double>("Costo")
                        .HasColumnType("double precision");

                    b.Property<string>("Llave")
                        .HasColumnType("text");

                    b.Property<int>("Tiempo")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TipoLicenciaId");

                    b.ToTable("TipoDeLicencia");
                });

            modelBuilder.Entity("QualfixAdmin.model.QualfixAdminData.Cliente", b =>
                {
                    b.HasOne("QualfixAdmin.model.QualfixAdminData.Ciudad", "Ciudad")
                        .WithMany("Clientes")
                        .HasForeignKey("CiudadId")
                        .HasConstraintName("FK_Cliente_Ciudad");

                    b.HasOne("QualfixAdmin.model.QualfixAdminData.Estado", "Estado")
                        .WithMany("Clientes")
                        .HasForeignKey("EstadoId")
                        .HasConstraintName("FK_Cliente_Estado");

                    b.HasOne("QualfixAdmin.model.QualfixAdminData.InformacionFiscals", "InformacionFiscal")
                        .WithMany("Clientes")
                        .HasForeignKey("InformacionFiscalId")
                        .HasConstraintName("FK_Cliente_InformacionFIscal");

                    b.HasOne("QualfixAdmin.model.QualfixAdminData.Pai", "Pais")
                        .WithMany("Clientes")
                        .HasForeignKey("PaisId")
                        .HasConstraintName("FK_Cliente_Pais");

                    b.Navigation("Ciudad");

                    b.Navigation("Estado");

                    b.Navigation("InformacionFiscal");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("QualfixAdmin.model.QualfixAdminData.Imagen", b =>
                {
                    b.HasOne("QualfixAdmin.model.QualfixAdminData.Reporte", "Reporte")
                        .WithMany("Imagenes")
                        .HasForeignKey("ReporteId");

                    b.Navigation("Reporte");
                });

            modelBuilder.Entity("QualfixAdmin.model.QualfixAdminData.InformacionFiscals", b =>
                {
                    b.HasOne("QualfixAdmin.model.QualfixAdminData.Ciudad", "Ciudad")
                        .WithMany("InformacionFiscals")
                        .HasForeignKey("CiudadId")
                        .HasConstraintName("FK_InformacionFIscal_Ciudad");

                    b.HasOne("QualfixAdmin.model.QualfixAdminData.Estado", "Estado")
                        .WithMany("InformacionFiscals")
                        .HasForeignKey("EstadoId")
                        .HasConstraintName("FK_InformacionFIscal_Estado");

                    b.HasOne("QualfixAdmin.model.QualfixAdminData.Pai", "Pais")
                        .WithMany("InformacionFiscals")
                        .HasForeignKey("PaisId")
                        .HasConstraintName("FK_InformacionFIscal_Pais");

                    b.HasOne("QualfixAdmin.model.QualfixAdminData.RegimenFiscal", "RegFiscal")
                        .WithMany("InformacionFiscals")
                        .HasForeignKey("RegFiscalId")
                        .HasConstraintName("FK_InformacionFIscal_RegimenFiscal");

                    b.Navigation("Ciudad");

                    b.Navigation("Estado");

                    b.Navigation("Pais");

                    b.Navigation("RegFiscal");
                });

            modelBuilder.Entity("QualfixAdmin.model.QualfixAdminData.Ciudad", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("InformacionFiscals");
                });

            modelBuilder.Entity("QualfixAdmin.model.QualfixAdminData.Estado", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("InformacionFiscals");
                });

            modelBuilder.Entity("QualfixAdmin.model.QualfixAdminData.InformacionFiscals", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("QualfixAdmin.model.QualfixAdminData.Pai", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("InformacionFiscals");
                });

            modelBuilder.Entity("QualfixAdmin.model.QualfixAdminData.RegimenFiscal", b =>
                {
                    b.Navigation("InformacionFiscals");
                });

            modelBuilder.Entity("QualfixAdmin.model.QualfixAdminData.Reporte", b =>
                {
                    b.Navigation("Imagenes");
                });
#pragma warning restore 612, 618
        }
    }
}
