# Usa una imagen de Node.js como base para construir la aplicación Angular
FROM node:16 AS build

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos de configuración
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código fuente
COPY . .

# Construye la aplicación Angular en modo producción
RUN npm run build --prod

# Usa una imagen ligera de Nginx para servir la aplicación construida
FROM nginx:alpine

# Copia los archivos del dist directamente (porque no hay carpeta intermedia)
COPY --from=build /app/dist/ /usr/share/nginx/html

# Expone el puerto 80 para servir la app
EXPOSE 80

# Configura Nginx para que sirva la aplicación
CMD ["nginx", "-g", "daemon off;"]

